version: '3.4'

services:
  desafiohubconexa:
    image: ${DOCKER_REGISTRY-}desafiohubconexa
    build:
      context: .
      dockerfile: DesafioHubConexa/Dockerfile

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
